teleop_twist_joy_node:
  ros__parameters:
    enable_button: 5
    enable_turbo_button: 7
    axis_linear:  { x: 4 }   # stick droit vertical (si chez toi câ€™est 5, mets 5)
    axis_angular: { yaw: 3 } # stick droit horizontal
    scale_linear:  { x: 0.6 }
    scale_angular: { yaw: 0.8 }
    scale_linear_turbo:  { x: 1.0 }
    scale_angular_turbo: { yaw: 1.2 }
    require_enable_button: true
